import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/header/header";
import Footer from "@/components/footer/footer";
import { ToastContainer } from "react-toastify";
// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });
// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Eslam",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body
        className={` antialiased dark:bg-gray-900 `}
      // className={`${geistSans.variable} ${geistMono.variable} antialiased dark:bg-gray-900 `}
      >
        <Header />
        {/* <h1>uuuuuuuuuuuuuuuuuuuuuuuuu</h1> */}
        {children}
        <ToastContainer />
        {/* <Footer /> */}
      </body>
    </html>
  );
}
